<?php
/**
 * @file
 * A companion module for interface changes to the date field.
 */

/**
 * Implements hook_help().
 */
function stanford_date_timepicker_help($path, $arg) {
  switch ($path) {
    case 'admin/help#stanford_date_timepicker':
      return '<p>' . t('If you have any questions please email %email.', array('%email' => 'helpsu@stanford.edu')) . '</p>';
  }
}

/**
 * Implements hook_permission().
 */
function stanford_date_timepicker_permission() {
  return array(
    'administer stanford date timepicker' => array(
      'title' => t('Administer Stanford date timepicker settings'),
      'description' => t('Administer Stanford date timepicker settings.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function stanford_date_timepicker_menu() {
  $items['admin/config/stanford-datetimepicker'] = array(
    'title' => 'Datetimepicker Configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('stanford_date_timepicker_config_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'stanford_date_timepicker.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_element_info_alter().
 */
function stanford_date_timepicker_element_info_alter(&$type) {

  // Remove the processing of the field and add our own.
  $type['date_popup']['#process'] = array('stanford_date_timepicker_date_popup_element_process');

}

/**
 * [stanford_date_timepicker_date_popup_element_process description]
 * @param  [type] $element    [description]
 * @param  [type] $form_state [description]
 * @param  [type] $form       [description]
 * @return [type]             [description]
 */
function stanford_date_timepicker_date_popup_element_process($element, &$form_state, $form) {

  if (date_hidden_element($element)) {
    return $element;
  }

  module_load_include('inc', 'date_api', 'date_api_elements');

  $element['#tree'] = TRUE;
  $element['#theme_wrappers'] = array('date_popup');

  $element['date'] = date_popup_process_date_part($element);
  $element['time'] = date_popup_process_time_part($element);

  // Add new timepicker variable...
  $element['date']['#attributes']['class'][] = 'stanford-datepicker';
  $element['time']['#attributes']['class'][] = 'stanford-timepicker';
  $element['time']['#attributes']['rel'][] = $element['#field']['field_name'];

  $granularity = date_format_order($element['#date_format']);
  $time_granularity = array_intersect($granularity, array('hour', 'minute', 'second'));
  $format = date_popup_format_to_popup_time(date_limit_format($element['#date_format'], $time_granularity), 'default');
  $format = stanford_date_timepicker_format_to_popup_time($format);

  $settings = array(
    'controlType' => 'select',
    'timeFormat' => $format,
  );

  $id = stanford_date_timepicker_js_settings_id($element['#id'], $element['#field']['field_name'], $settings);

  if (isset($element['#element_validate'])) {
    array_push($element['#element_validate'], 'date_popup_validate');
  }
  else {
    $element['#element_validate'] = array('date_popup_validate');
  }

  $context = array(
   'form' => $form,
  );

  drupal_alter('date_popup_process', $element, $form_state, $context);

  return $element;
}

/**
 * [stanford_date_timepicker_js_settings_id description]
 * @param  [type] $id       [description]
 * @param  [type] $func     [description]
 * @param  [type] $settings [description]
 * @return [type]           [description]
 */
function stanford_date_timepicker_js_settings_id($id, $field_name, $settings) {
  static $id_count = array();

  // We use a static array to account for possible multiple form_builder()
  // calls in the same request (form instance on 'Preview').
  if (!isset($id_count[$id])) {
    $id_count[$id] = 0;
  }

  // Increment the ids...Usefull for add another.
  $return_id = "$id-" . $id_count[$id]++;

  $js_settings = array();
  $js_settings['stanfordDateTimepicker'][$return_id] = array();
  $js_settings['stanfordDateTimepicker'][$return_id]['id'] = $id;
  $js_settings['stanfordDateTimepicker'][$return_id]['opt_settings'] = $settings;
  $js_settings['stanfordDateTimepicker'][$return_id]['selector'] = '.stanford-timepicker';

  drupal_add_js($js_settings, 'setting');
  return $return_id;
}

/**
 * [stanford_date_timepicker_format_to_popup_time description]
 * @param  [type] $string [description]
 * @return [type]         [description]
 */
function stanford_date_timepicker_format_to_popup_time($string) {
  $format = $string;
  $format = strtr($format, stanford_date_timepicker_timepicker_format_replacements());
  return $format;
}

/**
 * [stanford_date_timepicker_timepicker_format_replacements description]
 * @return [type] [description]
 */
function stanford_date_timepicker_timepicker_format_replacements() {
  return array(
    'A' => 'TT',
    'a' => 'tt',
    'i' => 'mm',
    // 'iA' => 'mmTT',
    // 'ia' => 'mmtt',
  );
}

/**
 * Implements hook_field_settings_form().
 */
function stanford_date_timepicker_field_settings_form($field, $instance, $has_data) {
  /*
   *$settings = $field['settings'];
   *$form['max_length'] = array(
   *  '#type' => 'textfield',
   *  '#title' => t('Maximum length'),
   *  '#default_value' => $settings['max_length'],
   *  '#required' => FALSE,
   *  '#element_validate' => array('_element_validate_integer_positive'),
   *  '#description' => t('The maximum length of the field in characters. Leave blank for an unlimited size.'),
   *);
   */
  $form = array();
  $settings = $field['settings'];

  return $form;
}


/**
 * Implements hook_js_alter().
 */
function stanford_date_timepicker_js_alter(&$javascript) {

  // Remove date popup js.
  // $path = drupal_get_path('module','date_popup') . "/date_popup.js";
  // unset($javascript[$path]);

  // Remove the timepicker functionality
  foreach($javascript['settings']['data'] as $index => $type) {
    if(isset($type['datePopup']) && is_array($type['datePopup'])) {
      $setting = array_pop($type['datePopup']);
      if($setting['func'] == 'timeEntry') {
        unset($javascript['settings']['data'][$index]);
      }
    }
  }

}

/**
 * Implements hook_preprocess().
 */
function stanford_date_timepicker_preprocess_html(&$variables) {
  // Add timepicker customizations.
  drupal_add_js(drupal_get_path('module', 'stanford_date_timepicker') . "/js/stanford_date_timepicker.js");

   // Dependencies from drupal core.
  drupal_add_library('system', 'ui.datepicker');
  drupal_add_library('system', 'ui.slider');
  // Dependency for this module.
  drupal_add_library('stanford_date_timepicker', 'jquery-ui-timepicker');
  // Add the settings to the page for the other timepicker classes.
  drupal_add_js(array(
    'stanford_date_timepicker' => array(
      'classes' => variable_get('timepicker_activation_class', ''),
      'default_date_format' => check_plain(variable_get('timepicker_default_date_format', 'yy-mm-dd')),
      'default_time_format' => check_plain(variable_get('timepicker_default_time_format', 'hh:mm')),
      'default_separator' => check_plain(variable_get('timepicker_default_separator', 'hh:mm')),
    )), 'setting');


}

/**
 *  Implements hook_library().
 */
function stanford_date_timepicker_library() {
  $path = libraries_get_path('jquery-ui-timepicker');
  $libraries['jquery-ui-timepicker'] = array(
    'title' => 'jQuery ui timepicker',
    'website' => 'https://github.com/trentrichardson/jQuery-Timepicker-Addon',
    'version' => '1.4',
    'js' => array(
      $path . '/jquery-ui-sliderAccess.js' => array(),
      $path . '/jquery-ui-timepicker-addon.js' => array(),
    ),
    'css' => array(
      $path . '/jquery-ui-timepicker-addon.css' => array(
        'type' => 'file',
        'media' => 'screen',
      ),
    ),
  );
  return $libraries;
}
